%% ----------------- MLR on Raw Predictors -----------------
% Author: Benjamin Pullen
% Date: 10/09/2025

%clear; close all; clc;

%% Load datasets
data = readtable("merged_flux_weather.xlsx");
bg_data = readtable("spring25_backgroundFluxes_continuous.xlsx");

%% Compute excess CH4 flux
flux_raw = data.CH4_Flux;
bg_flux = bg_data.CH4_Flux;
bg_mean = mean(bg_flux, 'omitnan');
bg_std  = std(bg_flux, 'omitnan');
bg_thresh = bg_mean + 3*bg_std;
excess_flux = flux_raw - bg_thresh;
excess_flux(excess_flux < 0) = 0; 
data.Excess_CH4_Flux = excess_flux;

%% Define raw predictors
% Full list
% predictorVars = data(:, { ...
%     'W_m2SolarRadiation', ...
%     'degreesWindDirection', ...
%     'm_sWindSpeed', ...
%     'm_sGustSpeed', ...
%     'degree_CAirTemperature', ...
%     'kPaVaporPressure', ...
%     'kPaAtmosphericPressure', ...
%     'kPaVPD', ...
%     'm3_m3WaterContent', ...
%     'degree_CSoilTemperature', ...
%     'mS_cmSaturationExtractEC', ...
%     'm3_m3WaterContent_1', ...
%     'degree_CSoilTemperature_1', ...
%     'mS_cmSaturationExtractEC_1', ...
%     'kPaMatricPotential', ...
%     'degree_CSoilTemperature_2', ...
%     'degree_C30CmSoilTemperature4', ...
%     'degree_C50CmSoilTemperature5', ...
%     'degree_C100CmSoilTemperature6' ...
%     }); 

% Reduced list
predictorVars = data(:, { ...
    'm_sWindSpeed', ...
    'kPaAtmosphericPressure', ...
    'kPaVPD', ...
    'm3_m3WaterContent', ...
    'degree_CSoilTemperature', ...
    'kPaMatricPotential', ...
    'degree_C100CmSoilTemperature6' ...
    }); 

predictorNames = predictorVars.Properties.VariableNames;
X = table2array(predictorVars);
y = data.Excess_CH4_Flux;

%% Fit multiple linear regression
mlrModel = fitlm(X, y, 'VarNames',[predictorNames, {'Excess_CH4_Flux'}]);

%% Display model summary
disp('--- Multiple Linear Regression on Raw Predictors ---');
disp(mlrModel);
fprintf('R² = %.3f, Adjusted R² = %.3f\n', mlrModel.Rsquared.Ordinary, mlrModel.Rsquared.Adjusted);

%% Plot observed vs predicted
yPred = predict(mlrModel, X);
figure('Position',[100 100 600 400]);
scatter(y, yPred, 50, 'filled', 'MarkerFaceColor',[0.3 0.7 0.4]); hold on;
plot([min(y) max(y)], [min(y) max(y)], 'r--', 'LineWidth',2);
xlabel('Observed Excess CH_4 Flux (µmol m^{-2} s^{-1})','FontSize',12);
ylabel('Predicted Excess CH_4 Flux (µmol m^{-2} s^{-1})','FontSize',12);
title('MLR: Observed vs Predicted Excess CH_4 Flux','FontSize',14);
grid on; box on;

%% Optional: Display significant predictors
sigPredictors = mlrModel.Coefficients.pValue < 0.05;
disp('Significant predictors (p < 0.05):');
disp(mlrModel.Coefficients(sigPredictors,:));
